name: 'TYPO3 Extension Repository Uploader'
description: 'This action can pack and upload an extension to the TYPO3 Extension Repository (TER)'
author: 'Kevin Ditscheid <kevin@the-coding-owl.de>'
runs:
  using: 'docker'
  image: 'Dockerfile'
branding:
  icon: 'upload'
  color: 'orange'
